import {
  ChevronRightIcon,
  EllipsisHorizontalIcon,
  CheckIcon,
  XCircleIcon,
  XMarkIcon,
  MagnifyingGlassIcon,
  Bars3BottomLeftIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  MinusIcon,
  Bars3Icon,
  ChevronLeftIcon,
  DocumentIcon,
  PencilIcon,
  EyeIcon,
  QuestionMarkCircleIcon,
  CogIcon,
  UserIcon,
  ArrowRightOnRectangleIcon,
  CalendarIcon,
  StarIcon,
  ArrowDownTrayIcon,
  HomeIcon,
  UsersIcon,
  FolderOpenIcon,
  ChevronUpDownIcon,
} from '@heroicons/react/24/solid';

// Export with the same names as lucide-react for drop-in replacement
export {
  ChevronRightIcon as ChevronRight,
  EllipsisHorizontalIcon as MoreHorizontal,
  CheckIcon,
  XCircleIcon as CircleIcon,
  XMarkIcon as XIcon,
  MagnifyingGlassIcon as SearchIcon,
  Bars3BottomLeftIcon as PanelLeftIcon,
  ArrowLeftIcon as ArrowLeft,
  ArrowRightIcon as ArrowRight,
  ChevronDownIcon,
  ChevronUpIcon,
  MinusIcon,
  Bars3Icon as GripVerticalIcon,
  ChevronLeftIcon,
  EllipsisHorizontalIcon as MoreHorizontalIcon,
  // Additional icons for stories
  DocumentIcon as FileIcon,
  PencilIcon,
  EyeIcon,
  QuestionMarkCircleIcon as HelpCircleIcon,
  CogIcon as SettingsIcon,
  UserIcon,
  ArrowRightOnRectangleIcon as LogOutIcon,
  CalendarIcon,
  StarIcon,
  ArrowDownTrayIcon as DownloadIcon,
  HomeIcon as Home,
  UsersIcon as Users,
  FolderOpenIcon,
  ChevronDownIcon as ChevronDown,
  ChevronUpDownIcon as ChevronsUpDown,
  CheckIcon as Check,
}; 